[package]
name = "aoc2016"
version = "0.1.0"
authors = ["Ryan V. <vanwarner@ieee.org"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.5"
array2d = "0.2.1"
